### ISSUE TITLE
Eliminate library dependencies created by code that is not enabled in ConfigurableFirmata.

### ISSUE THREAD

**Issue by finson** [finson/ConfigurableFirmata#9]
@soundanalogous said:

All of DeviceFirmata.cpp needs to be moved to DeviceFirmata.h or Luni and Bas64 will become hard dependencies of ConfigurableFirmata whether or not the user chooses to use DeviceFirmata.

**Comment by finson** [comment]
Jeff:  

I agree that this is an issue that needs to be solved.

However, I really dislike the "put it all in the include file" design.  It seems to me that the Arduino IDE already suffers from not really being a "normal" C++ development environment, and that things like this take it yet another step away, especially since it's caused by the way the IDE works.

Let me beat my head on the wall a little and then make a proposal.  At worst, developers could just move `feature.cpp` and `feature.h` from `optional/` to`src/` when they want to use it, but that's a pain.

More news as events warrant.

Doug

**Comment by soundanalogous** [comment]
Yeah I don't care for it either. People have been asking Arduino to change it for several years now but they refuse to make changes in order to keep things simple. One way around it is to write a makefile, but that means users would need to build from the command line rather than the IDE. However, there are people working on making CLI driven Arduino processes easier so this may not be a bad time to start adding makefiles to libraries. I'm also curious if the Arduino Create IDE works more favorably with libraries.

**Comment by soundanalogous** [comment]
Another solution is to host DeviceFirmata outside of ConfigurableFirmata like I did with [FirmataEncoder](https://github.com/firmata/FirmataEncoder).

**Comment by finson** [comment]
A couple of weeks ago we talked about scripting for testing.  After  
exploring build systems for a bit, I decided to give CMake a try.  I've  
actually compiled, linked, and uploaded Blink successfully that way.  Now  
I'm working on the scaffolding to detect connected devices, allocate  
configurations, make and load, then run clients to actually do the tests.  
I'm hoping that CMake can do at least some of that too.

So my libraries will have CMake files, at least.  Opinions about build  
systems seem to be right up there with languages!  I haven't had to deal  
with them other than Ant for several years, so I was kind of disappointed  
by the state of the art.  And Arduino is building their own, which I never  
think is a good idea ...

Doug

On Sun, 10 Jul 2016 20:48:15 -0700, Jeff Hoefs notifications@github.com  
wrote:

> Yeah I don't care for it either. People have been asking Arduino to  
> change it for several years now but they refuse to make changes in order  
> to keep >things simple. One way around it is to write a makefile, but  
> that means users would need to build from the command line rather than  
> the IDE. However, >there are people working on making CLI driven Arduino  
> processes easier so this may not be a bad time to start adding makefiles  
> to libraries. I'm also >curious if the Arduino Create IDE works more  
> favorably with libraries.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Using Opera's mail client: http://www.opera.com/mail/

**Comment by finson** [comment]
Jeff:  

I propose to you that the features be categorized as core, optional, or contributed.  The only change is moving the files around in the distribution, there is no change to the sources.  I created a branch and did a proof of concept implementation.  finson/FirmataWithDeviceFeature/b2.10-optional-features-idea.  I've attached a snapshot of the readme that explains how to enable/disable features.  I've tested the idea to the extent of starting with just the core features enabled in the ino file, then enabling and disabling the optional features one or two at a time.  Note that when you disable a feature, you can delete it from the sketch library directory.  This is not required, but it keeps the library list cleaner, and the library manager won't do it for you.

Doug

![readme-optional-features](https://cloud.githubusercontent.com/assets/1281452/16791219/a0529a26-4871-11e6-91ac-fc8872583ea1.PNG)

**Comment by soundanalogous** [comment]
I like your proposal. The only change I'd make is to not include the `features-contributed` directory as those libraries could just as well be hosted externally and the library authors should include an example sketch with their contributed library to demonstrate how to properly include it (rather than adding it to ConfigurableFirmata.ino as a commented out include, which would need to be updated each time an author creates a contributed library). Or maybe the `features-contributed` folder is included but it only contains a readme with a list and urls of all contributed libraries. Authors then submit a PR to add to that list (or it could be done via the wiki and then no PR is even required).

**Comment by finson** [comment]
How about if I just merge the Optional Features part of the idea branch back into b2.10 and we don't do anything about Contributed right now?  

That would give us the idea of a Core Features set and a relatively simple process for installing items from the Optional Features set.  All Features would be included in the ConfigurableFirmata distribution, organized as proposed and all subject to your commit authority.

If people want to write something to extend Firmata for a specific case, they can write a device driver and drop it in to their own sketch with no need for a new Sysex or anything like that.  There could be a process of "write an issue against Luni to add your device driver, we'll do a little gatekeeping, and if it looks okay, we'll add your URL to an online list of device drivers."  This is essentially the way new Arduino libraries get added.

 If there is a demand for supplying new features rather than device drivers, that's okay but a strategy to avoid continually expanding the allocated Sysex code space would be needed.  (That's where the device driver idea came from in the first place, after all!)  Perhaps having the relief valve of device drivers will mean that the super specialized, or weirdly unique, capabilities can be implemented as device drivers, and ideas that survive and look like a good general expansion of capability could then go into Optional Features, after vetting and so on.

Looking at it another way, Core and Optional (including DeviceFirmata) constitute ConfigurableFirmata, and 3rd party DeviceDriver implementations take the place of Contributed Features.  

So, shall I merge this branch back into b2.10 and we continue to develop there?

**Comment by soundanalogous** [comment]
SGTM. I think feature version reporting will also be helpful since we're breaking out the Optional features. I had an initial proposal here: https://github.com/firmata/protocol/issues/41. This would also eliminate the need to define pin modes for new features (unless new features use HW pins such as a SPI feature for example). I can work on that separately.

**Comment by finson** [comment]
Okay, I will do the merge of the idea branch into b2.10, leaving out the 'Contributed' aspect.

Eliminating pin modes for new features would be good.  Since pin mode means something specific in Arduino land, the overloaded usage as a general capability indicator is confusing and constraining (IMHO).  

Again, thinking of Device Drivers as a relief valve for new capabilities might reduce the pressure to be constantly defining new feature ids (Sysex subcommands) for the version reports proposed in  [firmata/protocol#41](https://github.com/firmata/protocol/issues/41).

**Comment by soundanalogous** [comment]
Yeah I think the device driver will allow me to reduce the ID to one byte in the feature query. Also for some features like Servo it is helpful to know which pins are supported, but that could be handled via a query to the Servo feature rather than relying on capability query response. Thus keeping pin modes just to input, input-pullup, output, analog-input, pwm, i2c, uart, spi. Even i2c, uart and spi may not be necessary at some point (once respective protocols are revised to support pin queries).

**Comment by finson** [comment]
Merged the revised layout branch into the b2.10 development branch.  There is now a features-optional directory outside of the src directory.  It holds the sources for features that a sketch author might want to include in an executable, but that most sketches will not need.  

commit: 755e53f3e86b00d0584b5143be5842375cfa9961
